version: '3'

services:
  db:
    container_name: citrus_pgsql
    image: postgres
    restart: always
    ports:
      - 127.0.0.1:15432:5432
    volumes:
      - ./pgsql_data/:/var/lib/postgresql/data/
    environment:
      - TZ=Asia/Shanghai
      - PGTZ=Asia/Shanghai
      - POSTGRES_PASSWORD=citrustriage
      - POSTGRES_DB=citrus